name: Maniacs Futsal Trophy Switzerland
favicon: null
layout_spectrum: 0.38351
typography_spectrum: 0.06135
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#303030'
    - '#8d8d8d'
    - '#ed1c24'
  brandStrength: 0.5
  lightness: 0.7908824079204351
  saturation: 0.25
  rhythmicContrast: 0.7791043997276574
purpose: []
